version: "3.7"
services:
  mongo:
    image: mongo:latest
    restart: always
    ports: 
      - "27019:27017"
  nikita:
    build: 
      context: .
      dockerfile: docker/nikita/Dockerfile
    depends_on: 
      - mongo
    environment:
      - DOCKER=1
    restart: always